---
version: '2.2'
services:
  code-server:
    image: codercom/code-server:${CS_IMAGE_TAG}
    command:
    - --disable-telemetry
    # Default port: 8080 (v2.x), 8443 (v1.x)
    - --port
    - '8443'
    # with server certificate and key
    #- --cert=/server.crt
    #- --cert-key=/server.key
    # v2.x only: --cert without any path will generate a self-signed certificate.
    #- --cert
    # v1.x: No --cert will generate a self-signed certificate.
    # for local access
    #- --allow-http --no-auth
    ports:
    - 8443:8443
    # for local access
    #- 127.0.0.1:8080:8443
    volumes:
    - "${PWD}/coder:/home/coder:rw"
    - "${PWD}/etc/sudoers.d/code-server:/etc/sudoers.d/code-server:ro"
    - "${PWD}/opt:/opt:rw"
    # comment out if you don't use the SSH protocol to access GitHub,...
    - "${SSH_AUTH_SOCK:-/tmp/ssh-coder/agent.dummy}:/ssh-agent:rw"
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
    # with server certificate and key
    #- "/path/to/server.crt:/server.crt:ro"
    #- "/path/to/server.key:/server.key:ro"
    environment:
      GOROOT: "${CS_GOROOT}"
      GOPATH: "${CS_GOPATH}"
      LD_LIBRARY_PATH: "${CS_LD_LIBRARY_PATH}"
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${CS_PATH}"
      SSH_AUTH_SOCK: /ssh-agent
